version: '3'
services:
  app:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "bundle exec puma -C config/puma.rb"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - '.env'

  postgres:
    image: postgres
    ports:
      - '5432:5432'
